[tool.mypy]
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_calls = false
disallow_untyped_defs = true
no_implicit_optional = true
show_error_codes = true
strict_equality = true
strict_optional = true
warn_redundant_casts = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true

[tool.ruff]
select = ["B", "C", "D", "E", "F", "I", "N", "S", "U", "W"]
ignore = ["E501", "D212", "D103", "D107"]
target-version = "py310"
src = ["resources"]

[tool.ruff.per-file-ignores]
"script.service.hyperion/resources/lib/monitor.py" = ["N802", "D102"]
"script.service.hyperion/resources/lib/hyperion/message_pb2.py" = ["D100"]
"__init__.py" = ["D104"]

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.isort]
force-single-line = true

[tool.ruff.pyupgrade]
keep-runtime-typing = true
